version: 2.1

jobs:
  build:
    executor: node
    working_directory: ~/node_circleci
    steps:
      - checkout
      - run: npm install
  test:
    executor: node
    working_directory: ~/node_circleci
    steps:
      - run: npm run test
workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
executors:
  node:
    resource_class: small
    docker:
      - image: cimg/node:14.18 # Should be same major version as .nvmrc