version: 2.1

jobs:
  build:
    executor: node
    steps:
      - checkout
      - run: npm install
  test:
    executor: node
    steps:
      - run: npm run test
executors:
  node:
    resource_class: small
    docker:
      - image: cimg/node:14.18 # Should be same major version as .nvmrc